Repository han16nah/my-ssd-test-repo, pull requests merged in 2022-03, with the labels that each got.

#21 Corr matrix
  src/oop_analysis.py
Labels: oop

#24 implemented issues 16 and 19
  src/oop_analysis.py
Labels: oop

#32 Unittest for corr function
  .flake8
  src/oop_analysis.py
  src/test_oop_analysis.py
Labels: testing

#30 commited test script with unittest for import of csv file
  src/test_oop_analysis.py
Labels: testing

#40 fixed bug in test function test_read_csv_as_df
  src/test/test_oop_analysis.py
Labels: bug, testing
